version: "3.7"
services:

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: sat4321
      MYSQL_USER: sat
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: satellites

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - "8080:8080"

networks:
  frontend:
  backend:
