version: "3.7"
services:

        web:
                build: .
                ports:
                        - "5000:5000"
                depends_on:
                        - db

        db:
                image: mysql:8.0
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                networks:
                        - backend
                environment:
                        MYSQL_ROOT_PASSWORD: sat4321
                        MYSQL_DATABASE: satellites

        adminer:
                image: adminer
                restart: always
                ports:
                        - "8080:8080"

networks:
        frontend:
        backend:
